import '@/styles/globals.css'
import { useCounter } from "@/hooks/useCounter";
import { useInput } from "@/hooks/useInput";

export default function App({ Component, pageProps }) {
  const count = useCounter();
  const input = useInput();

  return (
    <>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <Component {...pageProps} {...count} {...input}/>
    </>
  )
}
